name: Build

on:
  push:
    branches-ignore:
      - 'test/**'

jobs:
  build:

    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Build Docker Image
        run: |
          docker-compose build
      - name: Run tests
        run: |
          docker-compose run car_manager_api npm test
        env:
          IMAGE_TAG: ${{env.version}}-${{env.git-hash}}
